::mods_registerMod("mod_settlement", 1.8, "True Balance Mod settlement");
::mods_queue("mod_settlement", "mod_true_balance", function() {
::mods_hookBaseClass("entity/world/settlement", function(o) 
{
	::mods_override (o[o.SuperName], "updateRoster", function( _force = false )
	{
		local daysPassed = (this.Time.getVirtualTimeF() - this.m.LastRosterUpdate) / this.World.getTime().SecondsPerDay;

		if (!_force && this.m.LastRosterUpdate != 0 && daysPassed < 2)
		{
			return;
		}

		if (this.m.RosterSeed != 0)
		{
			this.Math.seedRandom(this.m.RosterSeed);
		}

		this.m.RosterSeed = this.Math.floor(this.Time.getRealTime() + this.Math.rand());
		this.m.LastRosterUpdate = this.Time.getVirtualTimeF();
		local roster = this.World.getRoster(this.getID());
		local current = roster.getAll();
		local iterations = this.Math.max(1, daysPassed / 2);
		local activeLocations = 0;

		foreach( loc in this.m.AttachedLocations )
		{
			if (loc.isActive())
			{
				activeLocations = ++activeLocations;
			}
		}

		local minRosterSizes = [
			0,
			3,
			5,
			7
		];
		local rosterMin = minRosterSizes[this.m.Size] + (this.isSouthern() ? 2 : 0);
		local rosterMax = minRosterSizes[this.m.Size] + activeLocations + (this.isSouthern() ? 1 : 0);

		if (this.World.FactionManager.getFaction(this.m.Factions[0]).getPlayerRelation() < 50)
		{
			rosterMin = rosterMin * (this.World.FactionManager.getFaction(this.m.Factions[0]).getPlayerRelation() / 50.0);
			rosterMax = rosterMax * (this.World.FactionManager.getFaction(this.m.Factions[0]).getPlayerRelation() / 50.0);
		}

		rosterMin = rosterMin * this.m.Modifiers.RecruitsMult;
		rosterMax = rosterMax * this.m.Modifiers.RecruitsMult;
		rosterMin = rosterMin + this.World.Assets.m.RosterSizeAdditionalMin;
		rosterMax = rosterMax + this.World.Assets.m.RosterSizeAdditionalMax;
		rosterMin = rosterMin * this.World.Assets.m.RecruitsMult;
		rosterMax = rosterMax * this.World.Assets.m.RecruitsMult;

		if (iterations < 7)
		{
			for( local i = 0; i < iterations; i = ++i )
			{
				for( local maxRecruits = this.Math.rand(this.Math.max(0, rosterMax / 2 - 1), rosterMax - 1); current.len() > maxRecruits;  )
				{
					local n = this.Math.rand(0, current.len() - 1);
					roster.remove(current[n]);
					current.remove(n);
				}
			}
		}
		else
		{
			roster.clear();
			current = [];
		}

		local maxRecruits = this.Math.rand(rosterMin, rosterMax);
		local draftList;
		draftList = clone this.m.DraftList;

		foreach( loc in this.m.AttachedLocations )
		{
			loc.onUpdateDraftList(draftList);
		}

		foreach( b in this.m.Buildings )
		{
			if (b != null)
			{
				b.onUpdateDraftList(draftList);
			}
		}

		foreach( s in this.m.Situations )
		{
			s.onUpdateDraftList(draftList);
		}

		this.World.Assets.getOrigin().onUpdateDraftList(draftList);

		while (maxRecruits > current.len())
		{
			local bro = roster.create("scripts/entity/tactical/player");
			bro.setStartValuesEx(draftList);
			current.push(bro);
		}

		this.World.Assets.getOrigin().onUpdateHiringRoster(roster);
	})
});
::mods_hookNewObject("entity/world/settlements/city_state", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_southern_background",
			"beggar_southern_background",
			"butcher_southern_background",
			"caravan_hand_southern_background",
			"caravan_hand_southern_background",
			"caravan_hand_southern_background",
			"gambler_southern_background",
			"daytaler_southern_background",
			"daytaler_southern_background",
			"historian_southern_background",
			"peddler_southern_background",
			"peddler_southern_background",
			"servant_southern_background",
			"shepherd_southern_background",
			"shepherd_southern_background",
			"tailor_southern_background",
			"thief_southern_background",
			"thief_southern_background",
			"disowned_noble_background",
			"sellsword_background",
			"cripple_southern_background",
			"eunuch_southern_background",
			"slave_background",
			"slave_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"manhunter_background",
			"manhunter_background",
			"manhunter_background",
			"nomad_background",
			"nomad_background",
			"nomad_background",
			"nomad_ranged_background",
			"nomad_ranged_background",
			"assassin_southern_background",
			"assassin_southern_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_southern_background",
			"beggar_southern_background",
			"butcher_southern_background",
			"caravan_hand_southern_background",
			"caravan_hand_southern_background",
			"caravan_hand_southern_background",
			"gambler_southern_background",
			"daytaler_southern_background",
			"daytaler_southern_background",
			"historian_southern_background",
			"peddler_southern_background",
			"peddler_southern_background",
			"servant_southern_background",
			"shepherd_southern_background",
			"shepherd_southern_background",
			"tailor_southern_background",
			"thief_southern_background",
			"disowned_noble_background",
			"sellsword_background",
			"cripple_southern_background",
			"eunuch_southern_background",
			"slave_background",
			"slave_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"slave_southern_background",
			"manhunter_background",
			"manhunter_background",
			"nomad_background",
			"nomad_background",
			"nomad_ranged_background",
			"assassin_southern_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_coast_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"historian_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"eunuch_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"historian_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"eunuch_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_farm_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"gambler_background",
			"farmhand_background",
			"farmhand_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"miller_background",
			"miller_background",
			"minstrel_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"tailor_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"gambler_background",
			"farmhand_background",
			"farmhand_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"miller_background",
			"miller_background",
			"minstrel_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"tailor_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_farming_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"beggar_background",
			"butcher_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"daytaler_background",
			"farmhand_background",
			"farmhand_background",
			"farmhand_background",
			"farmhand_background",
			"historian_background",
			"juggler_background",
			"militia_background",
			"militia_background",
			"miller_background",
			"miller_background",
			"miller_background",
			"minstrel_background",
			"minstrel_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"shepherd_background",
			"tailor_background",
			"vagabond_background",
			"adventurous_noble_background",
			"bastard_background",
			"hedge_knight_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"swordmaster_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"beggar_background",
			"butcher_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"daytaler_background",
			"farmhand_background",
			"farmhand_background",
			"farmhand_background",
			"farmhand_background",
			"historian_background",
			"juggler_background",
			"militia_background",
			"militia_background",
			"miller_background",
			"miller_background",
			"miller_background",
			"minstrel_background",
			"minstrel_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"shepherd_background",
			"tailor_background",
			"vagabond_background",
			"adventurous_noble_background",
			"bastard_background",
			"hedge_knight_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"swordmaster_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_fishing_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"graverobber_background",
			"historian_background",
			"juggler_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"monk_background",
			"cripple_background",
			"eunuch_background",
			"peddler_background",
			"flagellant_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"servant_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"adventurous_noble_background",
			"bastard_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"swordmaster_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"graverobber_background",
			"historian_background",
			"juggler_background",
			"killer_on_the_run_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"monk_background",
			"cripple_background",
			"eunuch_background",
			"peddler_background",
			"flagellant_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"servant_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"adventurous_noble_background",
			"bastard_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"swordmaster_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_forest_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"bowyer_background",
			"bowyer_background",
			"brawler_background",
			"gambler_background",
			"gravedigger_background",
			"hunter_background",
			"hunter_background",
			"lumberjack_background",
			"lumberjack_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"refugee_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"bowyer_background",
			"bowyer_background",
			"brawler_background",
			"gambler_background",
			"gravedigger_background",
			"hunter_background",
			"hunter_background",
			"lumberjack_background",
			"lumberjack_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"refugee_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_lumber_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"bowyer_background",
			"bowyer_background",
			"brawler_background",
			"butcher_background",
			"cultist_background",
			"daytaler_background",
			"hunter_background",
			"hunter_background",
			"hunter_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"lumberjack_background",
			"lumberjack_background",
			"lumberjack_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"peddler_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"retired_soldier_background",
			"cripple_background",
			"eunuch_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"bowyer_background",
			"bowyer_background",
			"brawler_background",
			"butcher_background",
			"cultist_background",
			"daytaler_background",
			"hunter_background",
			"hunter_background",
			"hunter_background",
			"killer_on_the_run_background",
			"lumberjack_background",
			"lumberjack_background",
			"lumberjack_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"peddler_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"retired_soldier_background",
			"cripple_background",
			"eunuch_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_mountains_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"apprentice_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"gravedigger_background",
			"graverobber_background",
			"juggler_background",
			"mason_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"ratcatcher_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"sellsword_background",
			"sellsword_background",
			"squire_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"hedge_knight_background",
			"hedge_knight_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"apprentice_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"gravedigger_background",
			"graverobber_background",
			"juggler_background",
			"mason_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"ratcatcher_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"sellsword_background",
			"sellsword_background",
			"squire_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"hedge_knight_background",
			"hedge_knight_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_snow_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"brawler_background",
			"daytaler_background",
			"gravedigger_background",
			"graverobber_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"vagabond_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"hedge_knight_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"cripple_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"brawler_background",
			"daytaler_background",
			"gravedigger_background",
			"graverobber_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"vagabond_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"hedge_knight_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"squire_background",
			"cripple_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_snow_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"brawler_background",
			"brawler_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"farmhand_background",
			"gravedigger_background",
			"graverobber_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"peddler_background",
			"flagellant_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"sellsword_background",
			"swordmaster_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"brawler_background",
			"brawler_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"farmhand_background",
			"gravedigger_background",
			"graverobber_background",
			"killer_on_the_run_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"peddler_background",
			"flagellant_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"sellsword_background",
			"swordmaster_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_steppe_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"gravedigger_background",
			"hunter_background",
			"hunter_background",
			"juggler_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"flagellant_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"tailor_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"sellsword_background",
			"sellsword_background",
			"swordmaster_background",
			"hedge_knight_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"gravedigger_background",
			"hunter_background",
			"hunter_background",
			"juggler_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"flagellant_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"tailor_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"sellsword_background",
			"sellsword_background",
			"swordmaster_background",
			"hedge_knight_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_steppe_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"beggar_background",
			"bowyer_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"gravedigger_background",
			"graverobber_background",
			"historian_background",
			"hunter_background",
			"juggler_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"minstrel_background",
			"flagellant_background",
			"peddler_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"refugee_background",
			"servant_background",
			"shepherd_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"bastard_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"swordmaster_background",
			"cripple_background",
			"eunuch_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"beggar_background",
			"bowyer_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"gravedigger_background",
			"graverobber_background",
			"historian_background",
			"hunter_background",
			"juggler_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"minstrel_background",
			"flagellant_background",
			"peddler_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"refugee_background",
			"servant_background",
			"shepherd_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"bastard_background",
			"disowned_noble_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"swordmaster_background",
			"cripple_background",
			"eunuch_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_swamp_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"cultist_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"flagellant_background",
			"flagellant_background",
			"gravedigger_background",
			"graverobber_background",
			"historian_background",
			"juggler_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"monk_background",
			"peddler_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"retired_soldier_background",
			"sellsword_background",
			"swordmaster_background",
			"cripple_background",
			"eunuch_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"cultist_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"flagellant_background",
			"flagellant_background",
			"gravedigger_background",
			"graverobber_background",
			"historian_background",
			"juggler_background",
			"killer_on_the_run_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"monk_background",
			"peddler_background",
			"poacher_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"disowned_noble_background",
			"hedge_knight_background",
			"retired_soldier_background",
			"sellsword_background",
			"swordmaster_background",
			"cripple_background",
			"eunuch_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_tundra_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"brawler_background",
			"brawler_background",
			"brawler_background",
			"gambler_background",
			"cultist_background",
			"daytaler_background",
			"farmhand_background",
			"gravedigger_background",
			"graverobber_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"shepherd_background",
			"shepherd_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"sellsword_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"eunuch_background",
			"hedge_knight_background",
			"hedge_knight_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"brawler_background",
			"brawler_background",
			"brawler_background",
			"gambler_background",
			"cultist_background",
			"daytaler_background",
			"farmhand_background",
			"gravedigger_background",
			"graverobber_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"shepherd_background",
			"shepherd_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"sellsword_background",
			"squire_background",
			"swordmaster_background",
			"cripple_background",
			"eunuch_background",
			"hedge_knight_background",
			"hedge_knight_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/large_tundra_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"brawler_background",
			"brawler_background",
			"caravan_hand_background",
			"cultist_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"gravedigger_background",
			"graverobber_background",
			"hunter_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"monk_background",
			"peddler_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"shepherd_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"bastard_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"sellsword_background",
			"swordmaster_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"brawler_background",
			"brawler_background",
			"caravan_hand_background",
			"cultist_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"gravedigger_background",
			"graverobber_background",
			"hunter_background",
			"killer_on_the_run_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"minstrel_background",
			"monk_background",
			"peddler_background",
			"poacher_background",
			"ratcatcher_background",
			"shepherd_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"bastard_background",
			"disowned_noble_background",
			"raider_background",
			"sellsword_background",
			"swordmaster_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_coast_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"historian_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"monk_background",
			"peddler_background",
			"ratcatcher_background",
			"servant_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"swordmaster_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"historian_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"monk_background",
			"peddler_background",
			"ratcatcher_background",
			"servant_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"sellsword_background",
			"swordmaster_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_farm_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"gambler_background",
			"houndmaster_background",
			"farmhand_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"minstrel_background",
			"ratcatcher_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"disowned_noble_background",
			"sellsword_background",
			"squire_background",
			"squire_background",
			"cripple_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"gambler_background",
			"houndmaster_background",
			"farmhand_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"minstrel_background",
			"ratcatcher_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"disowned_noble_background",
			"sellsword_background",
			"squire_background",
			"squire_background",
			"cripple_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_fishing_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"graverobber_background",
			"historian_background",
			"juggler_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"messenger_background",
			"militia_background",
			"monk_background",
			"peddler_background",
			"flagellant_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"cripple_background",
			"eunuch_background",
			"sellsword_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"graverobber_background",
			"historian_background",
			"juggler_background",
			"killer_on_the_run_background",
			"messenger_background",
			"militia_background",
			"monk_background",
			"peddler_background",
			"flagellant_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"cripple_background",
			"eunuch_background",
			"sellsword_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_forest_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"bowyer_background",
			"bowyer_background",
			"brawler_background",
			"butcher_background",
			"daytaler_background",
			"gravedigger_background",
			"hunter_background",
			"lumberjack_background",
			"lumberjack_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"retired_soldier_background",
			"squire_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"bowyer_background",
			"bowyer_background",
			"brawler_background",
			"butcher_background",
			"daytaler_background",
			"gravedigger_background",
			"hunter_background",
			"lumberjack_background",
			"lumberjack_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"disowned_noble_background",
			"disowned_noble_background",
			"retired_soldier_background",
			"squire_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_lumber_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"bowyer_background",
			"bowyer_background",
			"brawler_background",
			"butcher_background",
			"daytaler_background",
			"historian_background",
			"hunter_background",
			"hunter_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"lumberjack_background",
			"lumberjack_background",
			"lumberjack_background",
			"militia_background",
			"flagellant_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"tailor_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"cripple_background",
			"eunuch_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"bowyer_background",
			"bowyer_background",
			"brawler_background",
			"butcher_background",
			"daytaler_background",
			"historian_background",
			"hunter_background",
			"hunter_background",
			"killer_on_the_run_background",
			"lumberjack_background",
			"lumberjack_background",
			"lumberjack_background",
			"militia_background",
			"flagellant_background",
			"poacher_background",
			"poacher_background",
			"tailor_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"cripple_background",
			"eunuch_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_mining_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"apprentice_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"juggler_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"peddler_background",
			"ratcatcher_background",
			"servant_background",
			"shepherd_background",
			"thief_background",
			"thief_background",
			"vagabond_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"apprentice_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"juggler_background",
			"killer_on_the_run_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"peddler_background",
			"ratcatcher_background",
			"servant_background",
			"shepherd_background",
			"thief_background",
			"vagabond_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_mountains_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"apprentice_background",
			"houndmaster_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"mason_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"miner_background",
			"miner_background",
			"servant_background",
			"shepherd_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"retired_soldier_background",
			"sellsword_background",
			"sellsword_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"apprentice_background",
			"houndmaster_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"mason_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"miner_background",
			"miner_background",
			"servant_background",
			"shepherd_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"retired_soldier_background",
			"sellsword_background",
			"sellsword_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_snow_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"brawler_background",
			"brawler_background",
			"cultist_background",
			"daytaler_background",
			"gravedigger_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"miner_background",
			"monk_background",
			"ratcatcher_background",
			"refugee_background",
			"vagabond_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"brawler_background",
			"brawler_background",
			"cultist_background",
			"daytaler_background",
			"gravedigger_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"miner_background",
			"monk_background",
			"ratcatcher_background",
			"refugee_background",
			"vagabond_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"deserter_background",
			"disowned_noble_background",
			"raider_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_snow_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"brawler_background",
			"brawler_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"gravedigger_background",
			"gravedigger_background",
			"graverobber_background",
			"hunter_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"lumberjack_background",
			"militia_background",
			"miner_background",
			"peddler_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"disowned_noble_background",
			"cripple_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"brawler_background",
			"brawler_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"gravedigger_background",
			"gravedigger_background",
			"graverobber_background",
			"hunter_background",
			"killer_on_the_run_background",
			"lumberjack_background",
			"militia_background",
			"miner_background",
			"peddler_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"disowned_noble_background",
			"cripple_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_steppe_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"hunter_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"hunter_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"refugee_background",
			"servant_background",
			"vagabond_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_steppe_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"daytaler_background",
			"historian_background",
			"hunter_background",
			"mason_background",
			"militia_background",
			"minstrel_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"refugee_background",
			"servant_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"adventurous_noble_background",
			"cripple_background",
			"poacher_background",
			"poacher_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"bowyer_background",
			"caravan_hand_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"daytaler_background",
			"historian_background",
			"hunter_background",
			"mason_background",
			"militia_background",
			"minstrel_background",
			"peddler_background",
			"ratcatcher_background",
			"refugee_background",
			"refugee_background",
			"servant_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"adventurous_noble_background",
			"cripple_background",
			"poacher_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_swamp_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"beggar_background",
			"butcher_background",
			"cultist_background",
			"gravedigger_background",
			"hunter_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"monk_background",
			"flagellant_background",
			"ratcatcher_background",
			"wildman_background",
			"witchhunter_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"beggar_background",
			"butcher_background",
			"cultist_background",
			"gravedigger_background",
			"hunter_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"monk_background",
			"flagellant_background",
			"ratcatcher_background",
			"wildman_background",
			"witchhunter_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"disowned_noble_background",
			"raider_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_swamp_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"beggar_background",
			"cultist_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"flagellant_background",
			"graverobber_background",
			"historian_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"militia_background",
			"militia_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"disowned_noble_background",
			"cripple_background",
			"anatomist_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"beggar_background",
			"cultist_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"flagellant_background",
			"graverobber_background",
			"historian_background",
			"killer_on_the_run_background",
			"militia_background",
			"militia_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"disowned_noble_background",
			"cripple_background",
			"anatomist_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_tundra_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"houndmaster_background",
			"bowyer_background",
			"brawler_background",
			"daytaler_background",
			"gravedigger_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"paladin_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"houndmaster_background",
			"bowyer_background",
			"brawler_background",
			"daytaler_background",
			"gravedigger_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"disowned_noble_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background",
			"sellsword_background",
			"paladin_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/medium_tundra_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"bowyer_background",
			"brawler_background",
			"brawler_background",
			"butcher_background",
			"cultist_background",
			"daytaler_background",
			"gravedigger_background",
			"graverobber_background",
			"hunter_background",
			"killer_on_the_run_background",
			"killer_on_the_run_background",
			"messenger_background",
			"militia_background",
			"minstrel_background",
			"monk_background",
			"peddler_background",
			"poacher_background",
			"poacher_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"bowyer_background",
			"brawler_background",
			"brawler_background",
			"butcher_background",
			"cultist_background",
			"daytaler_background",
			"gravedigger_background",
			"graverobber_background",
			"hunter_background",
			"killer_on_the_run_background",
			"messenger_background",
			"militia_background",
			"minstrel_background",
			"monk_background",
			"peddler_background",
			"poacher_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"wildman_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_coast_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"fisherman_background",
			"fisherman_background",
			"houndmaster_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"fisherman_background",
			"fisherman_background",
			"houndmaster_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"witchhunter_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"raider_background",
			"raider_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_farm_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"farmhand_background",
			"farmhand_background",
			"houndmaster_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"miller_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"farmhand_background",
			"farmhand_background",
			"houndmaster_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"miller_background",
			"adventurous_noble_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_farming_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"daytaler_background",
			"daytaler_background",
			"farmhand_background",
			"farmhand_background",
			"farmhand_background",
			"farmhand_background",
			"miller_background",
			"miller_background",
			"ratcatcher_background",
			"tailor_background",
			"vagabond_background",
			"poacher_background",
			"poacher_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"daytaler_background",
			"daytaler_background",
			"farmhand_background",
			"farmhand_background",
			"farmhand_background",
			"farmhand_background",
			"miller_background",
			"miller_background",
			"ratcatcher_background",
			"tailor_background",
			"vagabond_background",
			"poacher_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_fishing_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"beggar_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"peddler_background",
			"tailor_background",
			"vagabond_background",
			"vagabond_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"beggar_background",
			"daytaler_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"fisherman_background",
			"gravedigger_background",
			"peddler_background",
			"tailor_background",
			"vagabond_background",
			"vagabond_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_forest_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"bowyer_background",
			"brawler_background",
			"daytaler_background",
			"hunter_background",
			"hunter_background",
			"lumberjack_background",
			"militia_background",
			"militia_background",
			"wildman_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"bowyer_background",
			"brawler_background",
			"daytaler_background",
			"hunter_background",
			"hunter_background",
			"lumberjack_background",
			"militia_background",
			"militia_background",
			"wildman_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_lumber_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"bowyer_background",
			"bowyer_background",
			"butcher_background",
			"daytaler_background",
			"lumberjack_background",
			"lumberjack_background",
			"lumberjack_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"wildman_background",
			"hunter_background",
			"hunter_background",
			"tailor_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"bowyer_background",
			"bowyer_background",
			"butcher_background",
			"daytaler_background",
			"lumberjack_background",
			"lumberjack_background",
			"lumberjack_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"wildman_background",
			"hunter_background",
			"hunter_background",
			"tailor_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_mining_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"brawler_background",
			"daytaler_background",
			"graverobber_background",
			"mason_background",
			"messenger_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"peddler_background",
			"thief_background",
			"thief_background",
			"poacher_background",
			"poacher_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"brawler_background",
			"daytaler_background",
			"graverobber_background",
			"mason_background",
			"messenger_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"miner_background",
			"peddler_background",
			"thief_background",
			"poacher_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_mountains_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"beggar_background",
			"brawler_background",
			"daytaler_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"vagabond_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"beggar_background",
			"brawler_background",
			"daytaler_background",
			"mason_background",
			"messenger_background",
			"militia_background",
			"militia_background",
			"vagabond_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_snow_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"houndmaster_background",
			"brawler_background",
			"cultist_background",
			"mason_background",
			"militia_background",
			"militia_background",
			"vagabond_background",
			"wildman_background",
			"witchhunter_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"houndmaster_background",
			"brawler_background",
			"cultist_background",
			"mason_background",
			"militia_background",
			"militia_background",
			"vagabond_background",
			"wildman_background",
			"witchhunter_background",
			"deserter_background",
			"deserter_background",
			"raider_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_snow_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"brawler_background",
			"brawler_background",
			"cultist_background",
			"daytaler_background",
			"lumberjack_background",
			"mason_background",
			"miner_background",
			"flagellant_background",
			"poacher_background",
			"poacher_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"brawler_background",
			"brawler_background",
			"cultist_background",
			"daytaler_background",
			"lumberjack_background",
			"mason_background",
			"miner_background",
			"flagellant_background",
			"poacher_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_steppe_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"brawler_background",
			"brawler_background",
			"cultist_background",
			"daytaler_background",
			"lumberjack_background",
			"mason_background",
			"miner_background",
			"flagellant_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"thief_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"brawler_background",
			"brawler_background",
			"cultist_background",
			"daytaler_background",
			"lumberjack_background",
			"mason_background",
			"miner_background",
			"flagellant_background",
			"poacher_background",
			"thief_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_steppe_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"daytaler_background",
			"peddler_background",
			"refugee_background",
			"tailor_background",
			"thief_background",
			"thief_background",
			"vagabond_background",
			"poacher_background",
			"poacher_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"beggar_background",
			"brawler_background",
			"caravan_hand_background",
			"gambler_background",
			"daytaler_background",
			"daytaler_background",
			"peddler_background",
			"refugee_background",
			"tailor_background",
			"thief_background",
			"vagabond_background",
			"poacher_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_swamp_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"cultist_background",
			"houndmaster_background",
			"daytaler_background",
			"hunter_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"cultist_background",
			"houndmaster_background",
			"daytaler_background",
			"hunter_background",
			"militia_background",
			"militia_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"wildman_background",
			"witchhunter_background",
			"bastard_background",
			"deserter_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_swamp_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"beggar_background",
			"cultist_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"flagellant_background",
			"poacher_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"beggar_background",
			"cultist_background",
			"cultist_background",
			"daytaler_background",
			"daytaler_background",
			"flagellant_background",
			"poacher_background",
			"poacher_background",
			"ratcatcher_background",
			"ratcatcher_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background",
			"witchhunter_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_tundra_fort", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"daytaler_background",
			"militia_background",
			"militia_background",
			"miner_background",
			"vagabond_background",
			"wildman_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"apprentice_background",
			"houndmaster_background",
			"daytaler_background",
			"militia_background",
			"militia_background",
			"miner_background",
			"vagabond_background",
			"wildman_background",
			"bastard_background",
			"deserter_background",
			"deserter_background",
			"retired_soldier_background",
			"retired_soldier_background"
		];
	}
});
::mods_hookNewObject("entity/world/settlements/small_tundra_village", function(o) 
{
	if (this.World.Assets.m.IsBrigand)
	{
		o.m.DraftList = [
			"brawler_background",
			"daytaler_background",
			"daytaler_background",
			"farmhand_background",
			"miner_background",
			"peddler_background",
			"poacher_background",
			"poacher_background",
			"shepherd_background",
			"tailor_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background"
		];
	}
	else
	{
		o.m.DraftList = [
			"brawler_background",
			"daytaler_background",
			"daytaler_background",
			"farmhand_background",
			"miner_background",
			"peddler_background",
			"poacher_background",
			"shepherd_background",
			"tailor_background",
			"vagabond_background",
			"wildman_background",
			"wildman_background"
		];
	}
});
})